### ISSUE TITLE
some problems about FLOPs

### ISSUE THREAD

**Issue by Lyn4444** [York-SDCNLab/Ghost-DeblurGAN#4] opened 2023-09-12 13:35 UTC
How do you calculate FLOPs, I try to calculate the FLOPs of your model

**Comment by AmaldevHari** [comment] 2023-09-12 19:47
Hi,
You can use the following to estimate the FLOPs of model:
https://github.com/1adrianb/pytorch-estimate-flops

**Comment by AmaldevHari** [comment] 2023-09-15 14:54
> How do you calculate FLOPs, I try to calculate the FLOPs of your model

Hi,
I am going to close this issue. If the problem is not resolved you can re-open.

**Closed as completed by AmaldevHari** 2023-09-15 14:54 UTC
